### PR TITLE
Add serialization library

### PR DESCRIPTION
**Pull request by joscha**
as discussed with @htdvisser.
I made https://github.com/thesolarnomad/lora-serialization a git subtree (using a branch `lib-only that strips away all the unit testing, etc.).

There are a few open questions:
* I currently don't have a device I can test this code on, so I am relying on the unit tests from the serialization library - would be great if someone can test this on actual hardware
* I had to add `#include "lora-serialization/src/Lora*.cpp"` to the .ino file in order to make it compile - I suspect when pulling in the library with the library manager, the .cpp files would be picked up automatically? Can anyone confirm or deny this?
* I left the `LICENSE`, `README.md`, `library.properties` and the `decoder.js` of the LoRa serialization library in the subtree, these can obviously be removed if needed.

### CODE REVIEW

**Comment by johanstokking** [comment]
Thanks @joscha! I think this is super useful. It bridges the gap between manual bitshifting and using protobufs.

We have to ways to integrate this: either integrate it fully, as part of The Things Uno SDK without external library dependencies, or keep it separate and let people import the two libraries.

For the first option, we'd need you to sign a committer license agreement. Bit of a hassle, but I can't help it. The advantage is also that then, we can make that JavaScript pre-loaded in the decoder payload function. Also, we'd need to go over the naming to make it more consistent, but that's a minor detail.

**Comment by joscha** [comment]
Glad you like it @johanstokking! There is no problem signing a committer license agreement as long as everything stays open source. I think ideally the encoder and decoder methods would be usable by more than just the Things Uno, so integrating it into this repository via a subtree would be favourable to forking it into here. I can change the name of things or provide a renamed version to integrate, but it would be great if fixes to the encoder/decoder methods/classes made in here would flow back to the original project. What do you think?

**Comment by johanstokking** [comment]
OK, I'll get back on this end of this month. Totally agreed with your last point, thanks.

**Comment by joscha** [comment]
@johanstokking Why at the end of the month? I am sorry if I offended, I was just hoping that the serialization/deserialization would be something more generally available. If the choice is between getting it into the Things Uno as its own thing or not at all, I am happy to make the changes you suggested and see if I can keep fixes between the two places in sync?!

**Comment by johanstokking** [comment]
We're considering the role of this SDK; should it be one library that does everything, or should we build several specialised libraries (e.g. RN interface, message encoding, etc), or should it be a composition of those. The developer experience is key here; we don't want people to install multiple libraries before their code compiles.

What I would suggest is maintaining the separate library for now, which users can easily use in combination with this SDK's `sendBytes()` method.

Regarding naming, I think this is useful for other purposes as well, not only for LoRa communication, that I would drop the name LoRa from the class names.

**Comment by joscha** [comment]
I saw a few things in this library that I was hoping to be able to (re-)use, even though I don't own a Things Uno, so I totally understand what you mean. What would you suggest as the library name?

**Comment by johanstokking** [comment]
I'd say something like `ValueSerializer`, or -`Minifier` ... generic like that?

Also, we're planning to have the same functionality for downlink as well, using an encoder payload function. This would essentially mean doing everything the other way around.

**Comment by joscha** [comment]
@johanstokking I added the encoder for the JS/TTN side: https://github.com/thesolarnomad/lora-serialization/blob/master/src/encoder.js

**Comment by johanstokking** [comment]
@joscha status update from our side: I'm happy to merge this in the new `TheThingsNetwork/arduino-library` repository if you raise a PR there.

Please use generic names for the class, not anything with LoRa. It's a brand name and we can use this beyond the scope of LoRa communication.

Finally, we're working on a new back-end and dashboard. There will be builtin support for encoding JSON to bytes as well.

On a side note: did you look at Protocol Buffers?

**Comment by joscha** [comment]
@johanstokking OK, will create a PR there - I updated the encoder side in JS to a point where it is congruent with the encoder on the C side, so we can probably use that in the back-end and dashboard.

I had a look at protocol buffers, I think it would work, but it seemed to me as if I needed to spend a fair bit of extra bytes in order to use it, as the types are not implicit, but part of the serialization if I understand correctly. I was trying to minimize the number of bytes, so I could leverage the maximum airtime to the fullest.

**Comment by FokkeZB** [comment]
@joscha thanks for your patience, I've moved the code:
https://github.com/TheThingsNetwork/arduino-library

Please be aware that te library was renamed from TheThingsUno to TheThingsNetwork

**Comment by johanstokking** [comment]
@joscha there is overhead, but you get schemas, versioning, backward compatibility, default values, validation and a language-neutral and platform-neutral support for free. We're considering supporting this side-by-side to the payload functions.

**Comment by joscha** [comment]
@FokkeZB no worries.
@johanstokking sure, I mean both are well established, cross platform/language. So maybe it makes more sense building those into the arduino library? Have you guys checked whether the current protobuf C++ implementation runs on Arduino and how big it is?

**Comment by johanstokking** [comment]
It's merely compiling your proto to ANSI C code, so that is what runs on your Arduino, not the framework itself. The footprint depends mostly on the size of your proto.

**Comment by joscha** [comment]
@johanstokking just had a look at the tutorial - looks quite fitting actually - so would you rather want to give this a try instead of the raw data serialization? I think if the TTN backend supported loading custom protobuf deserialization code, this might actually be the better choice long-term.

**Comment by johanstokking** [comment]
@joscha I think so too.

It's just a bit harder to get up and running, but I think we can make it easy enough. There are some good efforts to make it easier (and more compact) already, see for example https://github.com/nanopb/nanopb. We might want to offer a code generator for this in the dashboard, where you just have your C header and source generated with one button press.

**Comment by joscha** [comment]
@johanstokking OK, so do you think I should create a PR with the simple serialization code from https://github.com/thesolarnomad/lora-serialization (after removing the lora references) or would you want to work towards the protocol buffers?

**Comment by johanstokking** [comment]
@joscha Ideally I want to work towards protocol buffers, and I want this to be integrated in The Things Network Library for Arduino as well as built-in in the Handler and UI in the Dashboard.

Would you have time to contribute on the device part? If so, I'd be happy to schedule a brief call to exchange thoughts

**Comment by joscha** [comment]
@johanstokking this somehow got lost - sure, let's have a chat! My email is linked in my github profile, just drop me an email!

**Comment by joscha** [comment]
Hey, is this still something you are interested in @johanstokking ?

**Comment by johanstokking** [comment]
@joscha yes definitely. It would be great if you can work on a complete pull request (à la https://github.com/TheThingsNetwork/arduino-device-lib/pull/190/files), so:

- Arduino code and example
- Documentation
- Decoder library and example

We will make it possible to preload your library in the payload functions. So you won't have to copy/paste everything as Decoder. For that, I need to have the JavaScript library as separate file.

For this all to work and not to get in naming conflicts, we need you to find a unique name for the library. `LoraEncoder` first and foremost is confusing (it's not actually encoding LoRa) plus it violates the LoRa Alliance's trademark. We can't support and promote that name.

`joschaLPP` ?

**Comment by joscha** [comment]
@johanstokking sounds good, I can work on a PR! I can also change the name, not a problem at all. The JS part is available through npm (e.g. https://www.npmjs.com/package/lora-serialization) already, are you able to use npm as a means for pulling the library in (can change the package name there as well)? Is TTN still using `otto` as the interpreter for the JS functions or do we have node?

I also started looking at:
* https://github.com/nanopb/nanopb
* https://github.com/johanstokking/ttn-protobuf-demo
* https://github.com/dcodeIO/ProtoBuf.js

and I think I might be able to get that working as well potentially. The advantage of the protobuf is, that it is more versatile, the advantage of a custom library is that the lib can use half-bytes, etc. for encoding and save a few extra bits here and there.

What do you think?

**Comment by johanstokking** [comment]
Yes, I'm definitely in favour of supporting protobufs because of its versatility and compactness.

We actually already have silent support for it, in the form of `TheThingsMessage`, see https://github.com/TheThingsNetwork/arduino-device-lib/blob/master/src/TheThingsMessage.h.

I'm good with both approaches, but protobufs has my preference. We would also build a decoder in Go, which is faster. It wouldn't be very feasible with JavaScript anyway.

For the `lora-serialization` approach, we're indeed using Otto.

**Comment by johanstokking** [comment]
To get things integrated in the Handler, we want to support alternatives to the current JavaScript payload functions. Keep an eye here https://github.com/TheThingsNetwork/ttn/issues/519

**Comment by joscha** [comment]
@johanstokking I played around with protobuf and transformed one project - I am actually not sure if it is a good fit for TTN, yet, given that the default data types seem to be quite big. A data set of:

* unixtime
* latitude
* longitude
* uint8
* 2x uint16
* temperature
* humidity

is 21 bytes with my lib and about 38 (variably up to 45, but minimum seems to be 38) with nanopb.
The 38 bytes don't even transfer through my single channel gateway any more, probably the payload is too big, but I also think the ease-of-use might not warrant the 50% increase in message size... what do you think, shall we give "joschaLPP" (not sure I like that name, will think of something better, haha) a go?

**Pull request closed without merging**
